import fs from 'node:fs';
const path='assets/knight.glb',buffer=fs.readFileSync(path),failures=[];
const check=(condition,label)=>{if(!condition)failures.push(label);};
check(buffer.readUInt32LE(0)===0x46546c67,'GLB magic');check(buffer.readUInt32LE(4)===2,'glTF version');check(buffer.readUInt32LE(8)===buffer.length,'GLB declared length');
let at=12,json,bin;while(at<buffer.length){const n=buffer.readUInt32LE(at),type=buffer.readUInt32LE(at+4),data=buffer.subarray(at+8,at+8+n);if(type===0x4e4f534a)json=JSON.parse(data.toString());else if(type===0x004e4942)bin=data;at+=8+n;}
const counts={SCALAR:1,VEC2:2,VEC3:3,VEC4:4,MAT4:16},bytes={5121:1,5123:2,5125:4,5126:4},readers={5121:'readUInt8',5123:'readUInt16LE',5125:'readUInt32LE',5126:'readFloatLE'};
function accessor(i){const a=json.accessors[i],v=json.bufferViews[a.bufferView],nc=counts[a.type],size=bytes[a.componentType],stride=v.byteStride||nc*size,offset=(v.byteOffset||0)+(a.byteOffset||0),result=[];for(let k=0;k<a.count;k++)for(let c=0;c<nc;c++)result.push(bin[readers[a.componentType]](offset+k*stride+c*size));return {data:result,count:a.count,nc};}
let triangles=0,vertices=0,primitives=0,uvMin=Infinity,uvMax=-Infinity,normalError=0;const bounds={min:[Infinity,Infinity,Infinity],max:[-Infinity,-Infinity,-Infinity]};
for(const mesh of json.meshes)for(const p of mesh.primitives){primitives++;const pos=accessor(p.attributes.POSITION),uv=accessor(p.attributes.TEXCOORD_0),normal=accessor(p.attributes.NORMAL),index=accessor(p.indices);vertices+=pos.count;triangles+=index.count/3;check(pos.data.every(Number.isFinite),'finite positions');check(uv.data.every(Number.isFinite),'finite UV');check(normal.data.every(Number.isFinite),'finite normals');check(index.data.every(i=>Number.isInteger(i)&&i>=0&&i<pos.count),'valid indices');check(uv.count===pos.count,'UV cardinality');
 for(let k=0;k<pos.data.length;k++){const c=k%3;bounds.min[c]=Math.min(bounds.min[c],pos.data[k]);bounds.max[c]=Math.max(bounds.max[c],pos.data[k]);}for(const n of uv.data){uvMin=Math.min(uvMin,n);uvMax=Math.max(uvMax,n);}for(let k=0;k<normal.data.length;k+=3)normalError=Math.max(normalError,Math.abs(Math.hypot(...normal.data.slice(k,k+3))-1));}
check(normalError<1e-4,'unit normals');check(uvMin>=0&&uvMax<=1,'UV in atlas');check(json.images.every(im=>im.bufferView!==undefined&&!im.uri),'embedded textures');check(!json.buffers.some(b=>b.uri),'self contained geometry');
const report={passed:failures.length===0,failures,triangles,vertices,primitives,materials:json.materials.length,embeddedImages:json.images.length,bytes:buffer.length,bounds,uvRange:[uvMin,uvMax],maxNormalError:normalError,animations:json.animations?.length||0};
fs.writeFileSync('review/glb-validation.json',JSON.stringify(report,null,2));console.log(report);if(failures.length)process.exit(1);
